sudo: required
services:
  - docker
env:
  global:
    - IMAGE_NAME=soniaauvets/ros-bag-extractor
    - secure: CYsWLrgkzj64kaIEaBDcnBpUaTZHho9dUb7IIGR/0tR/+2u9zmS98+vCd/BozBtuQNXHLWsbqWXVLVzZDpNO7+0X+nqMAlezioQZzmPJnoKzDX+0oBCFHtn+upinX5uehFosKl5ikP6sDj6cXtcAs3Ki4420nU0m6LGzglWPFKNhcLmrNK4n2hq14nyv7iQOHSv0utox/ZgJj12abyJkBWelbEqEIB97PlIRkZcEdqn1aCCvQJFBcaLJIlR06wh3OIXZOhAeYOqG9K5YZ4eOrXwH/EraCP41nwu+sETQV+bWxCZGkyqrb8WA8FBqUcC/KwdIaOE2CLn+PV6lVg6yebY1jEg1V0M0GHMVDsG5DSToJzNZCOTkp4PnqOflannxNV8kYJY/2h7ifuAmEKA4386appqG5z9SJCi+iOOzC/lRVecZb1UB56rNMdqHlVHHcCJOoWn4yL5Wd5XULrxXzkmIDcUNX5SmdAplXjqlOnOG6Rso4kEGvVa3pRxRS5IG/7oe0Yzlt0D1MY28BwilDu0HcF+4ohz3JFcS+aK7Zjb6SBvN1nf0fetWdBy9fh6olGTSrlNUXorfk7BG+LIiCiBlKAa3kcQBekonCz2wxqvkJO9h2RplpGK5A+tGsy4Y87N3m8qhqxHLHl4xu74eMlfcSwh7azpIaZe69RyPUwM=
    - secure: h+2LXocf6EgBeQee21vVieULEk/9xg71F1/+A4azC1Z9aDUKKFhAqmw6Z72i9+m4iMXPpfx7iRQaHjTctd1AqPnNuGgJeI6lc70SeiaxyoWGwjRRMzMa01YyK5554cYgSAwlLj8kzu27/uaU4lkxcwKsftu1KzmoIZg2Xv9K9Suz72RGUctAlnNcxhGYZWKQkZ2xsRnm6RgM1vJLDgX2C20eBfbDyVSYS2YV/1roAUiEzFBQpoh6+WCJ7UVJz3dO8gskOBptd2TekQoviyAbT5cAK56UFYq6735ArSeItNrO5OImuBSl6pLSUBgv7A3W3+WCne4uN6tc57UhFYKwS8RQCqJnyK98NeTucHriY5VXLphCkCkSWPt4z4bnFeYFzYQWtL6vIwE8kNGo65gDa5MNw+fllBygMJAthxo6igIj6+o0lhK+d3aqJguRt7DUCa4bg/vCOpubIi/XJKleSR53OcilmgX7DOWLS5puviJO/pRZIe0GLJbRo2zsQyZc+0fImRfbU0ZIZoTMK26mZsQWD2dd3xShpGRhULdmXIsCF4j/YYSOOQ2gQYDuv9PoNzxd5gOdMsJlwW/Vl458t/gtx33OHLWUZ3rhFyuoXGht/h/5R7UskmuUXYrgxcuOAL8NdQUrAskfTKLK6pZj8NL4NQ0dfw0WHrIOjMSUdPo=
before_script:
  - version="$(cat VERSION)"
script:
  - docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" .
after_script:
  - docker images
before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}"
deploy:
  - provider: script
    script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${version}"
    on:
      branch: master
  - provider: script
    script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:dev"
    on:
      branch: dev
